### ISSUE TITLE
Power Button on the .bat doesn't start

### ISSUE THREAD

**Issue by wardenplays** [BinkanSalaryman/Discord-Audio-Stream-Bot#41]
I am trying to get this to work so I can stream some music for my online TTRPG game.

I got a bot token, and entered it into settings. I pressed the power button, and it turned yellow, but then back to red. I'm not sure what exactly I'm doing wrong.

When it turns yellow, it says "connecting to websocket"

**Comment by BinkanSalaryman** [comment]
Looks like a network issue on your or discord's side

**Comment by sephentos** [comment]
Having the same issue.

Screenrecording: https://i.imgur.com/1PEHx59.gif

app.log:

```
14:20:32.203 [AWT-EventQueue-0] INFO DiscordAudioStreamBot - Logging in...
14:20:44.046 [JDA MainWS-WriteThread] INFO DiscordAudioStreamBot - Logged off
```

**Comment by KaiRoman** [comment]
I seem to have the same problem as well, is there any way to fix this?

**Comment by KaiRoman** [comment]
Nevermind, i just needed to turn on server member intent. Warden and Sep you should try that

**Comment by BinkanSalaryman** [comment]
> Nevermind, i just needed to turn on server member intent. Warden and Sep you should try that

Yes, that is the problem to the issue. But admittedly the log file content is rather unhelpful because I get massive headaches when I try to get slf4j working. But I've got it working now, so... jda (discord api for java) will now spit out some information in the log too. Furthermore I extended the login status display to include "close code" messages. Sorry for the trouble I caused there!
